language: python
python:
  - "3.6"

services:
  - docker
  
install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
